[2024-04-14T20:31:03.899+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T20:31:03.916+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment.extract_task manual__2024-04-14T20:31:02.282600+00:00 [queued]>
[2024-04-14T20:31:03.922+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment.extract_task manual__2024-04-14T20:31:02.282600+00:00 [queued]>
[2024-04-14T20:31:03.923+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T20:31:03.936+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_task> on 2024-04-14 20:31:02.282600+00:00
[2024-04-14T20:31:03.943+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=487) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-14T20:31:03.944+0000] {standard_task_runner.py:63} INFO - Started process 489 to run task
[2024-04-14T20:31:03.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment', 'extract_task', 'manual__2024-04-14T20:31:02.282600+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment.py', '--cfg-path', '/tmp/tmpfd50wgf9']
[2024-04-14T20:31:03.945+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_task
[2024-04-14T20:31:03.982+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment.extract_task manual__2024-04-14T20:31:02.282600+00:00 [running]> on host d0408c96e778
[2024-04-14T20:31:04.053+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T20:31:02.282600+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T20:31:02.282600+00:00'
[2024-04-14T20:31:04.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T20:31:04.055+0000] {logging_mixin.py:188} INFO - /opt/***/dados/equipment.json
[2024-04-14T20:31:04.070+0000] {warnings.py:110} WARNING - /opt/***/dags/classes/load.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df.to_sql(table_name, con=engine, if_exists='append', index=False)

[2024-04-14T20:31:04.072+0000] {logging_mixin.py:188} INFO - 'Engine' object has no attribute 'cursor'
[2024-04-14T20:31:04.073+0000] {logging_mixin.py:188} INFO - Um total de 14 registros foram carregados na tabela equipment_teste_***
[2024-04-14T20:31:04.073+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-14T20:31:04.075+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T20:31:04.085+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=extract_and_load_equipment, task_id=extract_task, execution_date=20240414T203102, start_date=20240414T203103, end_date=20240414T203104
[2024-04-14T20:31:04.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T20:31:04.131+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T20:31:04.134+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
