[2024-04-15T00:07:25.775+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:07:25.798+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-09-24T00:00:00+00:00 [queued]>
[2024-04-15T00:07:25.809+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-09-24T00:00:00+00:00 [queued]>
[2024-04-15T00:07:25.812+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:07:25.828+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2022-09-24 00:00:00+00:00
[2024-04-15T00:07:25.841+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:07:25.844+0000] {standard_task_runner.py:63} INFO - Started process 2189 to run task
[2024-04-15T00:07:25.844+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'scheduled__2022-09-24T00:00:00+00:00', '--job-id', '713', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmpce26isyz']
[2024-04-15T00:07:25.845+0000] {standard_task_runner.py:91} INFO - Job 713: Subtask load_to_mysql
[2024-04-15T00:07:25.910+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-09-24T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:07:26.025+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2022-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-09-24T00:00:00+00:00'
[2024-04-15T00:07:26.027+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:07:26.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:07:26.028+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_to_mysql() missing 1 required positional argument: 'df'
[2024-04-15T00:07:26.038+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20220924T000000, start_date=20240415T000725, end_date=20240415T000726
[2024-04-15T00:07:26.056+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 713 for task load_to_mysql (load_to_mysql() missing 1 required positional argument: 'df'; 2189)
[2024-04-15T00:07:26.098+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:07:26.145+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:07:26.149+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
