[2024-04-14T20:26:37.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T20:26:37.923+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment.load_task manual__2024-04-14T20:26:34.174377+00:00 [queued]>
[2024-04-14T20:26:37.930+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment.load_task manual__2024-04-14T20:26:34.174377+00:00 [queued]>
[2024-04-14T20:26:37.931+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T20:26:37.944+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_task> on 2024-04-14 20:26:34.174377+00:00
[2024-04-14T20:26:37.958+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=409) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-14T20:26:37.960+0000] {standard_task_runner.py:63} INFO - Started process 411 to run task
[2024-04-14T20:26:37.960+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment', 'load_task', 'manual__2024-04-14T20:26:34.174377+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment.py', '--cfg-path', '/tmp/tmpxxc4vh00']
[2024-04-14T20:26:37.961+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask load_task
[2024-04-14T20:26:37.998+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment.load_task manual__2024-04-14T20:26:34.174377+00:00 [running]> on host d0408c96e778
[2024-04-14T20:26:38.112+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T20:26:34.174377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T20:26:34.174377+00:00'
[2024-04-14T20:26:38.113+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T20:26:38.125+0000] {warnings.py:110} WARNING - /opt/***/dags/classes/load.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df.to_sql(table_name, con=self.engine, if_exists='append', index=False)

[2024-04-14T20:26:38.126+0000] {logging_mixin.py:188} INFO - 'Engine' object has no attribute 'cursor'
[2024-04-14T20:26:38.126+0000] {logging_mixin.py:188} INFO - Um total de 14 registros foram carregados na tabela equipment_teste_***
[2024-04-14T20:26:38.127+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-14T20:26:38.128+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T20:26:38.136+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=extract_and_load_equipment, task_id=load_task, execution_date=20240414T202634, start_date=20240414T202637, end_date=20240414T202638
[2024-04-14T20:26:38.174+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T20:26:38.188+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T20:26:38.193+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
