[2024-04-15T00:05:16.991+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:05:17.024+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.transform_data scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2024-04-15T00:05:17.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.transform_data scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2024-04-15T00:05:17.039+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:05:17.075+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2022-04-30 00:00:00+00:00
[2024-04-15T00:05:17.091+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=824) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:05:17.094+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'transform_data', 'scheduled__2022-04-30T00:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmpd8owh8g2']
[2024-04-15T00:05:17.095+0000] {standard_task_runner.py:63} INFO - Started process 857 to run task
[2024-04-15T00:05:17.095+0000] {standard_task_runner.py:91} INFO - Job 319: Subtask transform_data
[2024-04-15T00:05:17.165+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.transform_data scheduled__2022-04-30T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:05:17.280+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2022-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-30T00:00:00+00:00'
[2024-04-15T00:05:17.281+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:05:17.282+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:05:17.283+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transform() missing 1 required positional argument: 'df'
[2024-04-15T00:05:17.293+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=transform_data, execution_date=20220430T000000, start_date=20240415T000517, end_date=20240415T000517
[2024-04-15T00:05:17.315+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 319 for task transform_data (transform() missing 1 required positional argument: 'df'; 857)
[2024-04-15T00:05:17.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:05:17.378+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:05:17.387+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
