[2024-04-15T00:49:55.929+0000] {processor.py:161} INFO - Started process (PID=3175) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:49:55.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:49:55.931+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:49:55.931+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:49:56.239+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:49:56.316+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:49:56.316+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:49:56.333+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:49:56.333+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_sensors to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T00:49:56.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.429 seconds
[2024-04-15T00:50:00.648+0000] {processor.py:161} INFO - Started process (PID=3185) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:00.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:50:00.650+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:00.650+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:00.968+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:00.978+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:00.978+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:50:00.997+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:00.997+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_sensors to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T00:50:01.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.376 seconds
[2024-04-15T00:50:18.603+0000] {processor.py:161} INFO - Started process (PID=3243) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:18.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:50:18.606+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:18.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:19.020+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:19.032+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:19.031+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:50:19.055+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:19.055+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_sensors to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T00:50:19.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.484 seconds
[2024-04-15T00:50:19.984+0000] {processor.py:161} INFO - Started process (PID=3245) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:19.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:50:19.987+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:19.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:20.442+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:20.459+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:20.458+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:50:20.489+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:20.488+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_sensors to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T00:50:20.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.539 seconds
[2024-04-15T00:50:50.739+0000] {processor.py:161} INFO - Started process (PID=3311) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:50.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:50:50.741+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:50.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:51.031+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:50:51.042+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:51.041+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:50:51.062+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:50:51.061+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_sensors to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T00:50:51.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.345 seconds
[2024-04-15T00:51:02.320+0000] {processor.py:161} INFO - Started process (PID=3324) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:02.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:51:02.322+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:02.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:02.629+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:02.638+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:02.638+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:51:02.657+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:02.656+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_sensors to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T00:51:02.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.363 seconds
[2024-04-15T00:51:12.728+0000] {processor.py:161} INFO - Started process (PID=3377) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:12.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:51:12.730+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:12.730+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:13.038+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:13.122+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:13.121+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:extract_and_load_equipment_failure_sensors
[2024-04-15T00:51:13.131+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:13.131+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:extract_and_load_equipment_failure_sensors
[2024-04-15T00:51:13.139+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:13.139+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:extract_and_load_equipment_failure_sensors
[2024-04-15T00:51:13.140+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:13.139+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:51:13.148+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:13.147+0000] {dag.py:3118} INFO - Creating ORM DAG for extract_and_load_equipment_failure_sensors
[2024-04-15T00:51:13.157+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:13.157+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-01 00:00:00+00:00, run_after=2022-01-02 00:00:00+00:00
[2024-04-15T00:51:13.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.648 seconds
[2024-04-15T00:51:44.368+0000] {processor.py:161} INFO - Started process (PID=3447) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:44.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:51:44.383+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:44.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:45.214+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:51:45.243+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:51:45.242+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:51:45.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.976 seconds
[2024-04-15T00:52:04.438+0000] {processor.py:161} INFO - Started process (PID=3455) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:52:04.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:52:04.444+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:52:04.443+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:52:57.786+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:52:57.768+0000] {timeout.py:68} ERROR - Process timed out, PID: 3455
[2024-04-15T00:53:35.250+0000] {processor.py:161} INFO - Started process (PID=3460) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:53:35.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:53:35.254+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:35.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:53:37.186+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:53:37.228+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:37.227+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '3f9e6e86-96c0-4cb2-b5d8-0fef2b4fe8f1'}
[2024-04-15T00:53:37.262+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:37.261+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220101T000000, start_date=20240415T005144, end_date=20240415T005337
[2024-04-15T00:53:37.284+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:53:37.288+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:37.288+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'manual__2024-04-15T00:51:40.831955+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '130d941a-bcb2-4bf7-b54c-ec574ad8187d'}
[2024-04-15T00:53:37.301+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:37.300+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20240415T005140, start_date=20240415T005142, end_date=20240415T005337
[2024-04-15T00:53:37.305+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data manual__2024-04-15T00:51:40.831955+00:00 [failed]> in state failed
[2024-04-15T00:53:37.309+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:37.309+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '3f9e6e86-96c0-4cb2-b5d8-0fef2b4fe8f1'}
[2024-04-15T00:53:37.320+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:37.320+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220101T000000, start_date=20240415T005144, end_date=20240415T005337
[2024-04-15T00:53:37.325+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:53:59.595+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:53:59.594+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:53:59.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 24.457 seconds
[2024-04-15T00:54:27.579+0000] {processor.py:161} INFO - Started process (PID=3478) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:27.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:54:27.588+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:27.587+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:29.862+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:29.911+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:29.908+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a423b309-4b85-4786-8f8b-8508e4ada83f'}
[2024-04-15T00:54:29.954+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:29.953+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220102T000000, start_date=20240415T005147, end_date=20240415T005429
[2024-04-15T00:54:29.970+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:29.974+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:29.974+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-14T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0d958abf-cc48-4fd4-961c-082a2db0f56d'}
[2024-04-15T00:54:29.984+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:29.984+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220114T000000, start_date=20240415T005150, end_date=20240415T005429
[2024-04-15T00:54:29.988+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-14T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:29.992+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:29.992+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-15T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'cbc20f28-bd4d-4b72-b9bb-934b38180fb0'}
[2024-04-15T00:54:30.001+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.001+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220115T000000, start_date=20240415T005151, end_date=20240415T005429
[2024-04-15T00:54:30.005+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-15T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:30.009+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.009+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-03T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '12b799a9-76b6-4d4a-85e7-49c389644b79'}
[2024-04-15T00:54:30.018+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.018+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220103T000000, start_date=20240415T005151, end_date=20240415T005430
[2024-04-15T00:54:30.023+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-03T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:30.027+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.026+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-05T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '184a4535-c68d-440e-a5f7-af2a40c737b0'}
[2024-04-15T00:54:30.035+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.034+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220105T000000, start_date=20240415T005151, end_date=20240415T005430
[2024-04-15T00:54:30.038+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-05T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:30.042+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.042+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-08T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd7f05507-46ac-4cd1-ae97-6a521a2d91e2'}
[2024-04-15T00:54:30.050+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.050+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220108T000000, start_date=20240415T005152, end_date=20240415T005430
[2024-04-15T00:54:30.054+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-08T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:30.059+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.059+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a423b309-4b85-4786-8f8b-8508e4ada83f'}
[2024-04-15T00:54:30.069+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.069+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220102T000000, start_date=20240415T005147, end_date=20240415T005430
[2024-04-15T00:54:30.074+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:30.078+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.078+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-04T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'dd0160de-ab7f-43f2-ad9f-972b57f07123'}
[2024-04-15T00:54:30.086+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.086+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220104T000000, start_date=20240415T005150, end_date=20240415T005430
[2024-04-15T00:54:30.091+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-04T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:30.116+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.115+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:54:30.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 2.682 seconds
[2024-04-15T00:54:30.211+0000] {processor.py:161} INFO - Started process (PID=3488) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:30.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:54:30.212+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:30.212+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:32.006+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:32.035+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.032+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-07T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '6bb65f12-efbb-4e13-aa72-f91eed421bdc'}
[2024-04-15T00:54:32.062+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.062+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220107T000000, start_date=20240415T005151, end_date=20240415T005432
[2024-04-15T00:54:32.078+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-07T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.082+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.081+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-06T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '9a1e2d25-9af6-44a0-9786-2fdfc12ec5ae'}
[2024-04-15T00:54:32.093+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.093+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220106T000000, start_date=20240415T005151, end_date=20240415T005432
[2024-04-15T00:54:32.097+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-06T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.100+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.099+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-14T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0d958abf-cc48-4fd4-961c-082a2db0f56d'}
[2024-04-15T00:54:32.110+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.110+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220114T000000, start_date=20240415T005150, end_date=20240415T005432
[2024-04-15T00:54:32.115+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-14T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.118+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.118+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-15T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'cbc20f28-bd4d-4b72-b9bb-934b38180fb0'}
[2024-04-15T00:54:32.129+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.129+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220115T000000, start_date=20240415T005151, end_date=20240415T005432
[2024-04-15T00:54:32.133+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-15T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.136+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.135+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-03T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '12b799a9-76b6-4d4a-85e7-49c389644b79'}
[2024-04-15T00:54:32.145+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.145+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220103T000000, start_date=20240415T005151, end_date=20240415T005432
[2024-04-15T00:54:32.149+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-03T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.152+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.151+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-05T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '184a4535-c68d-440e-a5f7-af2a40c737b0'}
[2024-04-15T00:54:32.161+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.161+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220105T000000, start_date=20240415T005151, end_date=20240415T005432
[2024-04-15T00:54:32.165+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-05T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.167+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.167+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-08T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd7f05507-46ac-4cd1-ae97-6a521a2d91e2'}
[2024-04-15T00:54:32.177+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.177+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220108T000000, start_date=20240415T005152, end_date=20240415T005432
[2024-04-15T00:54:32.180+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-08T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.183+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.183+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a423b309-4b85-4786-8f8b-8508e4ada83f'}
[2024-04-15T00:54:32.196+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.196+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220102T000000, start_date=20240415T005147, end_date=20240415T005432
[2024-04-15T00:54:32.202+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.207+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.206+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-04T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'dd0160de-ab7f-43f2-ad9f-972b57f07123'}
[2024-04-15T00:54:32.219+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.218+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220104T000000, start_date=20240415T005150, end_date=20240415T005432
[2024-04-15T00:54:32.222+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-04T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:32.242+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:32.242+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:54:32.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 2.084 seconds
[2024-04-15T00:54:39.784+0000] {processor.py:161} INFO - Started process (PID=3544) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:39.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:54:39.792+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:39.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:40.990+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:41.031+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:41.029+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-11T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '51bc5aeb-983d-44f6-8814-6ad0b68a7544'}
[2024-04-15T00:54:41.064+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:41.063+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220111T000000, start_date=20240415T005154, end_date=20240415T005441
[2024-04-15T00:54:41.081+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-11T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:41.112+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:41.111+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:54:41.140+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:41.139+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-16 00:00:00+00:00, run_after=2022-01-17 00:00:00+00:00
[2024-04-15T00:54:41.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.403 seconds
[2024-04-15T00:54:49.999+0000] {processor.py:161} INFO - Started process (PID=3546) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:50.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:54:50.003+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:50.002+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:51.518+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:54:51.698+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.697+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-12T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd358e47c-57b8-45ef-b020-8b44c83b4293'}
[2024-04-15T00:54:51.744+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.744+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220112T000000, start_date=20240415T005154, end_date=20240415T005451
[2024-04-15T00:54:51.761+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-12T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:51.764+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.764+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-10T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2b75d15d-1782-403b-b148-4b2f87076588'}
[2024-04-15T00:54:51.774+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.774+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220110T000000, start_date=20240415T005152, end_date=20240415T005451
[2024-04-15T00:54:51.778+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-10T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:51.781+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.781+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-13T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '75ace55b-539d-429d-a08f-77042961e11a'}
[2024-04-15T00:54:51.790+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.790+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220113T000000, start_date=20240415T005158, end_date=20240415T005451
[2024-04-15T00:54:51.793+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-13T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:54:51.829+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.828+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:54:51.848+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:54:51.848+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-19 00:00:00+00:00, run_after=2022-01-20 00:00:00+00:00
[2024-04-15T00:54:51.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.881 seconds
[2024-04-15T00:55:00.185+0000] {processor.py:161} INFO - Started process (PID=3555) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:00.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:55:00.187+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:00.187+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:00.912+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:00.946+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:00.945+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-12T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd358e47c-57b8-45ef-b020-8b44c83b4293'}
[2024-04-15T00:55:00.981+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:00.981+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220112T000000, start_date=20240415T005154, end_date=20240415T005500
[2024-04-15T00:55:01.002+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-12T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:01.008+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:01.007+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-10T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2b75d15d-1782-403b-b148-4b2f87076588'}
[2024-04-15T00:55:01.019+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:01.019+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220110T000000, start_date=20240415T005152, end_date=20240415T005501
[2024-04-15T00:55:01.026+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-10T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:01.030+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:01.029+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-09T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '51c3797e-6e4a-444c-a742-94901436b391'}
[2024-04-15T00:55:01.046+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:01.046+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220109T000000, start_date=20240415T005152, end_date=20240415T005501
[2024-04-15T00:55:01.052+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-09T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:01.074+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:01.073+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:55:01.103+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:01.102+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-22 00:00:00+00:00, run_after=2022-01-23 00:00:00+00:00
[2024-04-15T00:55:01.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.955 seconds
[2024-04-15T00:55:11.368+0000] {processor.py:161} INFO - Started process (PID=3567) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:11.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:55:11.372+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:11.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:12.389+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:12.424+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:12.423+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-17T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0f84bee1-e6aa-485f-9c16-ad8e1de9e003'}
[2024-04-15T00:55:12.463+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:12.462+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220117T000000, start_date=20240415T005448, end_date=20240415T005512
[2024-04-15T00:55:12.489+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-17T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:12.498+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:12.497+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-17T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0f84bee1-e6aa-485f-9c16-ad8e1de9e003'}
[2024-04-15T00:55:12.518+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:12.518+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220117T000000, start_date=20240415T005448, end_date=20240415T005512
[2024-04-15T00:55:12.526+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-17T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:12.556+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:12.554+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:55:12.589+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:12.589+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-25 00:00:00+00:00, run_after=2022-01-26 00:00:00+00:00
[2024-04-15T00:55:12.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.272 seconds
[2024-04-15T00:55:29.437+0000] {processor.py:161} INFO - Started process (PID=3580) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:29.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:55:29.441+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:29.441+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:30.391+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:30.424+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:30.423+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-16T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b77c69b3-c0b1-4956-91fe-651dd47d6f81'}
[2024-04-15T00:55:30.455+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:30.455+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220116T000000, start_date=20240415T005448, end_date=20240415T005530
[2024-04-15T00:55:30.471+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-16T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:30.476+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:30.475+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-18T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2a66c652-0e01-4323-b5a9-492722305b70'}
[2024-04-15T00:55:30.486+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:30.486+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220118T000000, start_date=20240415T005450, end_date=20240415T005530
[2024-04-15T00:55:30.490+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-18T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:30.509+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:30.507+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:55:30.540+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:30.539+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-28 00:00:00+00:00, run_after=2022-01-29 00:00:00+00:00
[2024-04-15T00:55:30.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.138 seconds
[2024-04-15T00:55:51.015+0000] {processor.py:161} INFO - Started process (PID=3632) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:51.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:55:51.018+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:51.018+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:51.952+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:55:52.038+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.038+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-20T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '4a970fdf-4873-4e1c-abcc-6c201b83bb3e'}
[2024-04-15T00:55:52.067+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.067+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220120T000000, start_date=20240415T005501, end_date=20240415T005552
[2024-04-15T00:55:52.083+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-20T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:52.087+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.087+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-19T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'ed868776-aad3-4d19-88a1-36ba1edcc7a6'}
[2024-04-15T00:55:52.096+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.096+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220119T000000, start_date=20240415T005501, end_date=20240415T005552
[2024-04-15T00:55:52.100+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-19T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:52.103+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.103+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-21T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a2758a77-bc43-43f3-99b1-b0f49dc27d25'}
[2024-04-15T00:55:52.113+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.112+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220121T000000, start_date=20240415T005501, end_date=20240415T005552
[2024-04-15T00:55:52.118+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-21T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:55:52.134+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.133+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:55:52.158+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:55:52.157+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-01-30 00:00:00+00:00, run_after=2022-01-31 00:00:00+00:00
[2024-04-15T00:55:52.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.176 seconds
[2024-04-15T00:56:02.118+0000] {processor.py:161} INFO - Started process (PID=3648) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:56:02.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:56:02.122+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:56:02.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:01.900+0000] {processor.py:161} INFO - Started process (PID=3660) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:01.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:57:01.903+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:01.902+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:31.103+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:31.135+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.134+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0e5751a4-dafe-4ccc-b899-1237534338ab'}
[2024-04-15T00:57:31.155+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.155+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220123T000000, start_date=20240415T005531, end_date=20240415T005731
[2024-04-15T00:57:31.167+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:31.170+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.169+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-24T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'abc3eef8-bb4e-451b-9b1c-9b8f0a94397f'}
[2024-04-15T00:57:31.178+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.178+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220124T000000, start_date=20240415T005532, end_date=20240415T005731
[2024-04-15T00:57:31.181+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-24T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:31.184+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.184+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-22T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'e8b9e62e-def0-4add-b588-f281fc975bf5'}
[2024-04-15T00:57:31.191+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.191+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220122T000000, start_date=20240415T005529, end_date=20240415T005731
[2024-04-15T00:57:31.194+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-22T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:31.196+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.196+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-29T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '42c3bd72-356d-47b3-a266-6e80ffc6c866'}
[2024-04-15T00:57:31.203+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.203+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220129T000000, start_date=20240415T005536, end_date=20240415T005731
[2024-04-15T00:57:31.206+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-29T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:31.209+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.208+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-25T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '4920fc81-d158-48bb-b5d9-451af4c49c82'}
[2024-04-15T00:57:31.215+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.215+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220125T000000, start_date=20240415T005536, end_date=20240415T005731
[2024-04-15T00:57:31.220+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-25T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:31.808+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.807+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:57:31.828+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:31.827+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-02 00:00:00+00:00, run_after=2022-02-03 00:00:00+00:00
[2024-04-15T00:57:31.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 30.042 seconds
[2024-04-15T00:57:45.964+0000] {processor.py:161} INFO - Started process (PID=3722) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:45.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:57:45.967+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:45.966+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:46.462+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:57:46.487+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.486+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-26T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'fe9ca0cd-f921-4169-a2c0-48bf227b82a0'}
[2024-04-15T00:57:46.510+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.509+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220126T000000, start_date=20240415T005536, end_date=20240415T005746
[2024-04-15T00:57:46.519+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-26T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.522+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.521+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0e5751a4-dafe-4ccc-b899-1237534338ab'}
[2024-04-15T00:57:46.530+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.529+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220123T000000, start_date=20240415T005531, end_date=20240415T005746
[2024-04-15T00:57:46.534+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.536+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.536+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-24T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'abc3eef8-bb4e-451b-9b1c-9b8f0a94397f'}
[2024-04-15T00:57:46.544+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.544+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220124T000000, start_date=20240415T005532, end_date=20240415T005746
[2024-04-15T00:57:46.547+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-24T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.549+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.549+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '379a0d76-25ff-4bcf-a91a-7c67bd8d8477'}
[2024-04-15T00:57:46.557+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.557+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220201T000000, start_date=20240415T005602, end_date=20240415T005746
[2024-04-15T00:57:46.560+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.563+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.562+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-30T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a734da34-aa14-4346-a02e-a650e2c1aa14'}
[2024-04-15T00:57:46.570+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.569+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220130T000000, start_date=20240415T005602, end_date=20240415T005746
[2024-04-15T00:57:46.573+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-30T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.575+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.575+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-22T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'e8b9e62e-def0-4add-b588-f281fc975bf5'}
[2024-04-15T00:57:46.583+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.583+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220122T000000, start_date=20240415T005529, end_date=20240415T005746
[2024-04-15T00:57:46.586+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-22T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.588+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.588+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-29T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '42c3bd72-356d-47b3-a266-6e80ffc6c866'}
[2024-04-15T00:57:46.597+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.597+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220129T000000, start_date=20240415T005536, end_date=20240415T005746
[2024-04-15T00:57:46.600+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-29T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.602+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.602+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-25T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '4920fc81-d158-48bb-b5d9-451af4c49c82'}
[2024-04-15T00:57:46.610+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.609+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220125T000000, start_date=20240415T005536, end_date=20240415T005746
[2024-04-15T00:57:46.613+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-25T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.615+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.615+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-26T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'fe9ca0cd-f921-4169-a2c0-48bf227b82a0'}
[2024-04-15T00:57:46.622+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.622+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220126T000000, start_date=20240415T005536, end_date=20240415T005746
[2024-04-15T00:57:46.626+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-26T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.629+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.628+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0e5751a4-dafe-4ccc-b899-1237534338ab'}
[2024-04-15T00:57:46.637+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.636+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220123T000000, start_date=20240415T005531, end_date=20240415T005746
[2024-04-15T00:57:46.640+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.643+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.642+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-24T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'abc3eef8-bb4e-451b-9b1c-9b8f0a94397f'}
[2024-04-15T00:57:46.649+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.649+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220124T000000, start_date=20240415T005532, end_date=20240415T005746
[2024-04-15T00:57:46.652+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-24T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.655+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.654+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '379a0d76-25ff-4bcf-a91a-7c67bd8d8477'}
[2024-04-15T00:57:46.661+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.661+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220201T000000, start_date=20240415T005602, end_date=20240415T005746
[2024-04-15T00:57:46.665+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.667+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.667+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-30T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a734da34-aa14-4346-a02e-a650e2c1aa14'}
[2024-04-15T00:57:46.674+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.674+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220130T000000, start_date=20240415T005602, end_date=20240415T005746
[2024-04-15T00:57:46.678+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-30T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.682+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.681+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-26T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'fe9ca0cd-f921-4169-a2c0-48bf227b82a0'}
[2024-04-15T00:57:46.691+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.691+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220126T000000, start_date=20240415T005536, end_date=20240415T005746
[2024-04-15T00:57:46.694+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-26T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:57:46.697+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.697+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'manual__2024-04-15T00:55:28.668547+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'c6dd2037-b17c-434f-9b52-7655bcef5e35'}
[2024-04-15T00:57:46.703+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.702+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20240415T005528, start_date=20240415T005536, end_date=20240415T005746
[2024-04-15T00:57:46.705+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data manual__2024-04-15T00:55:28.668547+00:00 [failed]> in state failed
[2024-04-15T00:57:46.712+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.711+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:57:46.734+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:57:46.734+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-05 00:00:00+00:00, run_after=2022-02-06 00:00:00+00:00
[2024-04-15T00:57:46.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 0.797 seconds
[2024-04-15T00:58:00.877+0000] {processor.py:161} INFO - Started process (PID=3730) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:58:00.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:58:00.879+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:00.878+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:58:02.254+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:58:02.276+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.275+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '379a0d76-25ff-4bcf-a91a-7c67bd8d8477'}
[2024-04-15T00:58:02.294+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.294+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220201T000000, start_date=20240415T005602, end_date=20240415T005802
[2024-04-15T00:58:02.301+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:58:02.304+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.303+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-30T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a734da34-aa14-4346-a02e-a650e2c1aa14'}
[2024-04-15T00:58:02.310+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.310+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220130T000000, start_date=20240415T005602, end_date=20240415T005802
[2024-04-15T00:58:02.312+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-30T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:58:02.315+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.314+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-27T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'bcce8218-2ee1-4631-9eab-3ebb750c50c5'}
[2024-04-15T00:58:02.321+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.321+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220127T000000, start_date=20240415T005536, end_date=20240415T005802
[2024-04-15T00:58:02.325+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-27T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:58:02.340+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.339+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:58:02.364+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:02.363+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-08 00:00:00+00:00, run_after=2022-02-09 00:00:00+00:00
[2024-04-15T00:58:02.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.506 seconds
[2024-04-15T00:58:32.491+0000] {processor.py:161} INFO - Started process (PID=3775) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:58:32.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:58:32.495+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:58:32.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:02.571+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:02.568+0000] {timeout.py:68} ERROR - Process timed out, PID: 3775
[2024-04-15T00:59:03.164+0000] {processor.py:161} INFO - Started process (PID=3788) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:03.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:59:03.167+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:03.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:06.165+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:06.214+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.212+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '085bbc17-2219-4d46-a502-e840a1197a87'}
[2024-04-15T00:59:06.245+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.245+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220202T000000, start_date=20240415T005736, end_date=20240415T005906
[2024-04-15T00:59:06.256+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:06.259+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.259+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-01-28T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '78dfa467-54ab-4e4b-a934-c668ddbe897c'}
[2024-04-15T00:59:06.268+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.267+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220128T000000, start_date=20240415T005550, end_date=20240415T005906
[2024-04-15T00:59:06.272+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-01-28T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:06.275+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.274+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-03T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '3ad5cc0e-1824-4c2b-be66-b4e60a26ff6c'}
[2024-04-15T00:59:06.283+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.283+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220203T000000, start_date=20240415T005736, end_date=20240415T005906
[2024-04-15T00:59:06.287+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-03T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:06.290+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.289+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '085bbc17-2219-4d46-a502-e840a1197a87'}
[2024-04-15T00:59:06.299+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.299+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220202T000000, start_date=20240415T005736, end_date=20240415T005906
[2024-04-15T00:59:06.304+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:06.327+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.326+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:59:06.351+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:06.351+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-11 00:00:00+00:00, run_after=2022-02-12 00:00:00+00:00
[2024-04-15T00:59:06.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 3.222 seconds
[2024-04-15T00:59:34.023+0000] {processor.py:161} INFO - Started process (PID=3812) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:34.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T00:59:34.025+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:34.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:35.077+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T00:59:35.116+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.115+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-07T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f8defece-ebc6-4f33-b038-7a8a7b0de185'}
[2024-04-15T00:59:35.146+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.146+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220207T000000, start_date=20240415T005802, end_date=20240415T005935
[2024-04-15T00:59:35.162+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-07T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:35.167+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.167+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-04T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '6b4ce0ac-780b-4993-8af6-6d0e4ef9aa55'}
[2024-04-15T00:59:35.180+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.180+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220204T000000, start_date=20240415T005737, end_date=20240415T005935
[2024-04-15T00:59:35.186+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-04T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:35.189+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.189+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-07T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f8defece-ebc6-4f33-b038-7a8a7b0de185'}
[2024-04-15T00:59:35.203+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.203+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220207T000000, start_date=20240415T005802, end_date=20240415T005935
[2024-04-15T00:59:35.209+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-07T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:35.214+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.213+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-06T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'fbac5018-cf67-4057-a0bb-6e0b03385eba'}
[2024-04-15T00:59:35.226+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.226+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220206T000000, start_date=20240415T005803, end_date=20240415T005935
[2024-04-15T00:59:35.233+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-06T00:00:00+00:00 [failed]> in state failed
[2024-04-15T00:59:35.251+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.250+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T00:59:35.281+0000] {logging_mixin.py:188} INFO - [2024-04-15T00:59:35.281+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-14 00:00:00+00:00, run_after=2022-02-15 00:00:00+00:00
[2024-04-15T00:59:35.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.321 seconds
[2024-04-15T01:00:04.002+0000] {processor.py:161} INFO - Started process (PID=3823) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:04.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:00:04.012+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:04.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:04.925+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:04.962+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:04.961+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-05T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '7440e0dd-f1c2-4eb3-87c1-e1a9187b2ae4'}
[2024-04-15T01:00:04.986+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:04.986+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220205T000000, start_date=20240415T005804, end_date=20240415T010004
[2024-04-15T01:00:05.001+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-05T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:00:05.005+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:05.004+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-08T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '3bd3918f-5431-4818-a4c7-6c8a3213e1a5'}
[2024-04-15T01:00:05.016+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:05.016+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220208T000000, start_date=20240415T005806, end_date=20240415T010005
[2024-04-15T01:00:05.021+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-08T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:00:05.039+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:05.038+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:00:05.071+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:05.071+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-16 00:00:00+00:00, run_after=2022-02-17 00:00:00+00:00
[2024-04-15T01:00:05.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.491 seconds
[2024-04-15T01:00:34.318+0000] {processor.py:161} INFO - Started process (PID=3854) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:34.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:00:34.321+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:34.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:35.738+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:35.778+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:35.777+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-05T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '7440e0dd-f1c2-4eb3-87c1-e1a9187b2ae4'}
[2024-04-15T01:00:35.811+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:35.811+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220205T000000, start_date=20240415T005804, end_date=20240415T010035
[2024-04-15T01:00:35.833+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-05T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:00:35.839+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:35.839+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-10T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b953d672-727e-48a7-a911-53363a65365a'}
[2024-04-15T01:00:35.858+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:35.857+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220210T000000, start_date=20240415T005903, end_date=20240415T010035
[2024-04-15T01:00:35.869+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-10T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:00:35.895+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:35.893+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:00:36.366+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:36.366+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-17 00:00:00+00:00, run_after=2022-02-18 00:00:00+00:00
[2024-04-15T01:00:36.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 2.094 seconds
[2024-04-15T01:00:44.209+0000] {processor.py:161} INFO - Started process (PID=3897) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:44.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:00:44.213+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:44.212+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:45.244+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:45.275+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:45.271+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-09T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f82765b7-4233-478b-a88e-680437af19a4'}
[2024-04-15T01:00:45.302+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:45.302+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220209T000000, start_date=20240415T005903, end_date=20240415T010045
[2024-04-15T01:00:45.320+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-09T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:00:45.337+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:45.336+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:00:45.362+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:45.362+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-20 00:00:00+00:00, run_after=2022-02-21 00:00:00+00:00
[2024-04-15T01:00:45.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.187 seconds
[2024-04-15T01:00:54.472+0000] {processor.py:161} INFO - Started process (PID=3913) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:00:54.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:00:54.474+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:00:54.474+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:00.028+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:00.049+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.048+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-12T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '064cf51e-3c67-4744-a010-500cc94d050c'}
[2024-04-15T01:01:00.070+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.070+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220212T000000, start_date=20240415T010034, end_date=20240415T010100
[2024-04-15T01:01:00.078+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-12T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:00.081+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.080+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-11T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '88dd1a0b-20c4-490e-8970-56a79d26f5a8'}
[2024-04-15T01:01:00.086+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.086+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220211T000000, start_date=20240415T010004, end_date=20240415T010100
[2024-04-15T01:01:00.089+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-11T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:00.091+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.091+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-13T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '26f7b85f-13dc-48f0-837b-a76ba5170125'}
[2024-04-15T01:01:00.097+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.097+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220213T000000, start_date=20240415T010005, end_date=20240415T010100
[2024-04-15T01:01:00.099+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-13T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:00.101+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.101+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-12T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '064cf51e-3c67-4744-a010-500cc94d050c'}
[2024-04-15T01:01:00.107+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.107+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220212T000000, start_date=20240415T010034, end_date=20240415T010100
[2024-04-15T01:01:00.110+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-12T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:00.140+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.139+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:01:00.156+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:00.155+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-22 00:00:00+00:00, run_after=2022-02-23 00:00:00+00:00
[2024-04-15T01:01:00.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 5.910 seconds
[2024-04-15T01:01:04.929+0000] {processor.py:161} INFO - Started process (PID=3925) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:04.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:01:04.931+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:04.930+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:05.778+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:05.803+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.802+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-11T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '88dd1a0b-20c4-490e-8970-56a79d26f5a8'}
[2024-04-15T01:01:05.824+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.824+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220211T000000, start_date=20240415T010004, end_date=20240415T010105
[2024-04-15T01:01:05.837+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-11T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:05.841+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.840+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-13T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '26f7b85f-13dc-48f0-837b-a76ba5170125'}
[2024-04-15T01:01:05.850+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.849+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220213T000000, start_date=20240415T010005, end_date=20240415T010105
[2024-04-15T01:01:05.854+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-13T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:05.857+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.856+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-16T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b02f1f45-7561-40ae-a99a-1fa7b8821233'}
[2024-04-15T01:01:05.866+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.865+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220216T000000, start_date=20240415T010039, end_date=20240415T010105
[2024-04-15T01:01:05.871+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-16T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:05.874+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.874+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-14T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '861b556f-fe49-49c5-816e-a714405e3ad7'}
[2024-04-15T01:01:05.884+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.883+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220214T000000, start_date=20240415T010035, end_date=20240415T010105
[2024-04-15T01:01:05.887+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-14T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:05.889+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.889+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-15T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a77fdf22-ad65-4067-9d48-92cc06bf91b4'}
[2024-04-15T01:01:05.898+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.898+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220215T000000, start_date=20240415T010039, end_date=20240415T010105
[2024-04-15T01:01:05.902+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-15T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:05.905+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.905+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-18T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'e564bcbe-771e-4b86-8eb7-f13731c40e87'}
[2024-04-15T01:01:05.920+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:05.918+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220218T000000, start_date=20240415T010044, end_date=20240415T010105
[2024-04-15T01:01:12.628+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-18T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:12.632+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:12.632+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-16T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b02f1f45-7561-40ae-a99a-1fa7b8821233'}
[2024-04-15T01:01:12.648+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:12.648+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220216T000000, start_date=20240415T010039, end_date=20240415T010112
[2024-04-15T01:01:12.770+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-16T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:12.795+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:12.795+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:01:12.822+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:12.821+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-25 00:00:00+00:00, run_after=2022-02-26 00:00:00+00:00
[2024-04-15T01:01:13.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 8.223 seconds
[2024-04-15T01:01:15.095+0000] {processor.py:161} INFO - Started process (PID=3942) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:15.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:01:15.099+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.098+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:15.733+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:15.764+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.763+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-17T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b095bab7-8514-407e-ac8b-b2bea9c7d9c4'}
[2024-04-15T01:01:15.794+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.794+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220217T000000, start_date=20240415T010045, end_date=20240415T010115
[2024-04-15T01:01:15.807+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-17T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:15.816+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.815+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-14T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '861b556f-fe49-49c5-816e-a714405e3ad7'}
[2024-04-15T01:01:15.830+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.830+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220214T000000, start_date=20240415T010035, end_date=20240415T010115
[2024-04-15T01:01:15.837+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-14T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:15.841+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.841+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-15T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a77fdf22-ad65-4067-9d48-92cc06bf91b4'}
[2024-04-15T01:01:15.854+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.853+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220215T000000, start_date=20240415T010039, end_date=20240415T010115
[2024-04-15T01:01:15.859+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-15T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:15.864+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.863+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-18T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'e564bcbe-771e-4b86-8eb7-f13731c40e87'}
[2024-04-15T01:01:15.876+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.875+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220218T000000, start_date=20240415T010044, end_date=20240415T010115
[2024-04-15T01:01:15.881+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-18T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:15.885+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.884+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-20T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '8294a389-e7d7-4250-878c-2cad86778741'}
[2024-04-15T01:01:15.896+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.896+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220220T000000, start_date=20240415T010053, end_date=20240415T010115
[2024-04-15T01:01:15.901+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-20T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:15.906+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.905+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-17T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b095bab7-8514-407e-ac8b-b2bea9c7d9c4'}
[2024-04-15T01:01:15.917+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.917+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220217T000000, start_date=20240415T010045, end_date=20240415T010115
[2024-04-15T01:01:15.922+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-17T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:15.940+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:15.939+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:01:16.256+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:16.256+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-02-28 00:00:00+00:00, run_after=2022-03-01 00:00:00+00:00
[2024-04-15T01:01:16.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.195 seconds
[2024-04-15T01:01:34.485+0000] {processor.py:161} INFO - Started process (PID=3968) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:34.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:01:34.488+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:34.487+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:35.621+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:01:35.673+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.671+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-19T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd0e7d6e5-46f2-4422-9c16-c8e158571416'}
[2024-04-15T01:01:35.700+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.700+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220219T000000, start_date=20240415T010045, end_date=20240415T010135
[2024-04-15T01:01:35.947+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-19T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:35.951+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.950+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-20T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '8294a389-e7d7-4250-878c-2cad86778741'}
[2024-04-15T01:01:35.960+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.960+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220220T000000, start_date=20240415T010053, end_date=20240415T010135
[2024-04-15T01:01:35.968+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-20T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:35.972+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.971+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-19T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd0e7d6e5-46f2-4422-9c16-c8e158571416'}
[2024-04-15T01:01:35.983+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.982+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220219T000000, start_date=20240415T010045, end_date=20240415T010135
[2024-04-15T01:01:35.988+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-19T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:35.992+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:35.992+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-21T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'ae421681-0606-4d70-b2d8-b2d8f0e49517'}
[2024-04-15T01:01:36.003+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:36.003+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220221T000000, start_date=20240415T010054, end_date=20240415T010135
[2024-04-15T01:01:36.007+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-21T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:01:36.027+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:36.026+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:01:36.045+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:01:36.045+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-03 00:00:00+00:00, run_after=2022-03-04 00:00:00+00:00
[2024-04-15T01:01:36.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.597 seconds
[2024-04-15T01:02:00.604+0000] {processor.py:161} INFO - Started process (PID=3999) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:00.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:02:00.606+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:00.606+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:04.632+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:04.660+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.659+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'fd440d54-958f-4267-9d4b-1e6ab0148f23'}
[2024-04-15T01:02:04.686+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.685+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220223T000000, start_date=20240415T010105, end_date=20240415T010204
[2024-04-15T01:02:04.698+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:04.703+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.702+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-24T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '18edda55-37ae-4c72-b0fc-13398590fed0'}
[2024-04-15T01:02:04.715+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.715+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220224T000000, start_date=20240415T010105, end_date=20240415T010204
[2024-04-15T01:02:04.721+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-24T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:04.724+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.724+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'fd440d54-958f-4267-9d4b-1e6ab0148f23'}
[2024-04-15T01:02:04.732+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.732+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220223T000000, start_date=20240415T010105, end_date=20240415T010204
[2024-04-15T01:02:04.736+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:04.740+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.739+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-22T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2d6f00e8-81ea-4ce0-89d2-c7dbb0a67ca9'}
[2024-04-15T01:02:04.747+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.747+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220222T000000, start_date=20240415T010105, end_date=20240415T010204
[2024-04-15T01:02:04.751+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-22T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:04.754+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.754+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-26T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '65c53792-469e-4b8a-9611-d5d68d7f61eb'}
[2024-04-15T01:02:04.763+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.763+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220226T000000, start_date=20240415T010118, end_date=20240415T010204
[2024-04-15T01:02:04.768+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-26T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:04.773+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.772+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-25T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2bc15d58-6be7-4f95-a3f1-a1e1e09e49ab'}
[2024-04-15T01:02:04.784+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.783+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220225T000000, start_date=20240415T010118, end_date=20240415T010204
[2024-04-15T01:02:04.788+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-25T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:04.808+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.808+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:02:04.831+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:04.831+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-06 00:00:00+00:00, run_after=2022-03-07 00:00:00+00:00
[2024-04-15T01:02:04.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 4.136 seconds
[2024-04-15T01:02:34.743+0000] {processor.py:161} INFO - Started process (PID=4036) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:34.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:02:34.745+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:34.745+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:35.424+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:35.448+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:35.448+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-28T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'e03cc613-824f-4a07-8639-0c8709c700e3'}
[2024-04-15T01:02:35.474+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:35.474+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220228T000000, start_date=20240415T010135, end_date=20240415T010235
[2024-04-15T01:02:35.485+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-28T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:35.498+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:35.498+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:02:35.738+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:35.738+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-08 00:00:00+00:00, run_after=2022-03-09 00:00:00+00:00
[2024-04-15T01:02:35.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.023 seconds
[2024-04-15T01:02:45.022+0000] {processor.py:161} INFO - Started process (PID=4100) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:45.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:02:45.024+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:45.024+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:46.524+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:46.551+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.551+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-27T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '831f9a77-09a0-472b-aacf-0f4b02dff44a'}
[2024-04-15T01:02:46.579+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.579+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220227T000000, start_date=20240415T010135, end_date=20240415T010246
[2024-04-15T01:02:46.591+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-27T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:46.594+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.593+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '68c22328-cf92-4714-be3c-d47e61146258'}
[2024-04-15T01:02:46.600+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.600+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220301T000000, start_date=20240415T010135, end_date=20240415T010246
[2024-04-15T01:02:46.603+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:46.606+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.606+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a37176a7-da59-4232-a121-fe84b1afa198'}
[2024-04-15T01:02:46.612+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.612+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220302T000000, start_date=20240415T010135, end_date=20240415T010246
[2024-04-15T01:02:46.615+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:46.617+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.616+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-02-27T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '831f9a77-09a0-472b-aacf-0f4b02dff44a'}
[2024-04-15T01:02:46.623+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.623+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220227T000000, start_date=20240415T010135, end_date=20240415T010246
[2024-04-15T01:02:46.626+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-02-27T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:46.657+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.656+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:02:46.674+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:46.674+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-11 00:00:00+00:00, run_after=2022-03-12 00:00:00+00:00
[2024-04-15T01:02:46.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.683 seconds
[2024-04-15T01:02:55.269+0000] {processor.py:161} INFO - Started process (PID=4102) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:55.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:02:55.271+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:55.270+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:57.060+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:02:57.081+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.080+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-01T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '68c22328-cf92-4714-be3c-d47e61146258'}
[2024-04-15T01:02:57.102+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.101+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220301T000000, start_date=20240415T010135, end_date=20240415T010257
[2024-04-15T01:02:57.109+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-01T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.111+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.111+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-02T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a37176a7-da59-4232-a121-fe84b1afa198'}
[2024-04-15T01:02:57.117+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.116+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220302T000000, start_date=20240415T010135, end_date=20240415T010257
[2024-04-15T01:02:57.119+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-02T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.121+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.121+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-03T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f4f16ab9-6764-41ea-86f1-69f7829c9656'}
[2024-04-15T01:02:57.126+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.126+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220303T000000, start_date=20240415T010142, end_date=20240415T010257
[2024-04-15T01:02:57.129+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-03T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.131+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.131+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-05T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '9315d331-5f68-49ee-b5aa-d2c833103a46'}
[2024-04-15T01:02:57.136+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.136+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220305T000000, start_date=20240415T010142, end_date=20240415T010257
[2024-04-15T01:02:57.139+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-05T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.141+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.140+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-04T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'ff88ba73-575f-4862-b0f5-32fb98318eaf'}
[2024-04-15T01:02:57.146+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.146+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220304T000000, start_date=20240415T010159, end_date=20240415T010257
[2024-04-15T01:02:57.148+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-04T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.150+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.150+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-06T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b85701df-7dc1-4373-b3c3-8627e3905c83'}
[2024-04-15T01:02:57.155+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.155+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220306T000000, start_date=20240415T010236, end_date=20240415T010257
[2024-04-15T01:02:57.157+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-06T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.159+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.159+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-03T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f4f16ab9-6764-41ea-86f1-69f7829c9656'}
[2024-04-15T01:02:57.164+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.163+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220303T000000, start_date=20240415T010142, end_date=20240415T010257
[2024-04-15T01:02:57.166+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-03T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:02:57.194+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.194+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:02:57.209+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:02:57.208+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-14 00:00:00+00:00, run_after=2022-03-15 00:00:00+00:00
[2024-04-15T01:02:57.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.968 seconds
[2024-04-15T01:03:05.579+0000] {processor.py:161} INFO - Started process (PID=4112) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:05.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:03:05.582+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:05.581+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:07.749+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:07.772+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.772+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-05T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '9315d331-5f68-49ee-b5aa-d2c833103a46'}
[2024-04-15T01:03:07.796+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.796+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220305T000000, start_date=20240415T010142, end_date=20240415T010307
[2024-04-15T01:03:07.805+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-05T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.808+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.808+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-04T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'ff88ba73-575f-4862-b0f5-32fb98318eaf'}
[2024-04-15T01:03:07.816+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.816+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220304T000000, start_date=20240415T010159, end_date=20240415T010307
[2024-04-15T01:03:07.819+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-04T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.821+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.821+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-08T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '58ca18f8-e230-4b5c-aaf7-4af8560f8521'}
[2024-04-15T01:03:07.828+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.828+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220308T000000, start_date=20240415T010240, end_date=20240415T010307
[2024-04-15T01:03:07.831+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-08T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.833+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.833+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-06T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'b85701df-7dc1-4373-b3c3-8627e3905c83'}
[2024-04-15T01:03:07.840+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.839+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220306T000000, start_date=20240415T010236, end_date=20240415T010307
[2024-04-15T01:03:07.843+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-06T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.845+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.845+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-07T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '9e945c00-6ad3-48a9-a751-f0d789770639'}
[2024-04-15T01:03:07.852+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.852+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220307T000000, start_date=20240415T010238, end_date=20240415T010307
[2024-04-15T01:03:07.855+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-07T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.857+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.857+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-09T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a13bf505-ed9d-4cff-a41f-a461127f28ff'}
[2024-04-15T01:03:07.862+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.862+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220309T000000, start_date=20240415T010240, end_date=20240415T010307
[2024-04-15T01:03:07.865+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-09T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.867+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.867+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-10T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0d628c24-ee8b-4981-86ef-110a4a377491'}
[2024-04-15T01:03:07.873+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.872+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220310T000000, start_date=20240415T010243, end_date=20240415T010307
[2024-04-15T01:03:07.875+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-10T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.877+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.877+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-08T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '58ca18f8-e230-4b5c-aaf7-4af8560f8521'}
[2024-04-15T01:03:07.883+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.883+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220308T000000, start_date=20240415T010240, end_date=20240415T010307
[2024-04-15T01:03:07.886+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-08T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:07.899+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.899+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:03:07.918+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:07.918+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-17 00:00:00+00:00, run_after=2022-03-18 00:00:00+00:00
[2024-04-15T01:03:08.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 2.583 seconds
[2024-04-15T01:03:16.004+0000] {processor.py:161} INFO - Started process (PID=4170) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:16.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:03:16.009+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:16.008+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:20.219+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:20.242+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.241+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-07T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '9e945c00-6ad3-48a9-a751-f0d789770639'}
[2024-04-15T01:03:20.266+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.265+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220307T000000, start_date=20240415T010238, end_date=20240415T010320
[2024-04-15T01:03:20.485+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-07T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.487+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.487+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-09T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'a13bf505-ed9d-4cff-a41f-a461127f28ff'}
[2024-04-15T01:03:20.493+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.493+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220309T000000, start_date=20240415T010240, end_date=20240415T010320
[2024-04-15T01:03:20.496+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-09T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.497+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.497+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-10T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0d628c24-ee8b-4981-86ef-110a4a377491'}
[2024-04-15T01:03:20.503+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.503+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220310T000000, start_date=20240415T010243, end_date=20240415T010320
[2024-04-15T01:03:20.505+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-10T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.507+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.507+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-11T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '4b2f96c3-3cd3-4124-b952-f1dd5a031d3e'}
[2024-04-15T01:03:20.512+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.512+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220311T000000, start_date=20240415T010250, end_date=20240415T010320
[2024-04-15T01:03:20.515+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-11T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.517+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.516+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-13T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '20735987-b137-474f-9cc9-9a3b68de003c'}
[2024-04-15T01:03:20.522+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.522+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220313T000000, start_date=20240415T010250, end_date=20240415T010320
[2024-04-15T01:03:20.525+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-13T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.526+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.526+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-12T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'eaa82fe9-f2b9-456f-a0b7-fe3a1a1e3a05'}
[2024-04-15T01:03:20.532+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.531+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220312T000000, start_date=20240415T010250, end_date=20240415T010320
[2024-04-15T01:03:20.534+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-12T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.536+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.536+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-11T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '4b2f96c3-3cd3-4124-b952-f1dd5a031d3e'}
[2024-04-15T01:03:20.542+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.541+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220311T000000, start_date=20240415T010250, end_date=20240415T010320
[2024-04-15T01:03:20.544+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-11T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:20.570+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.569+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:03:20.584+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:20.583+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-20 00:00:00+00:00, run_after=2022-03-21 00:00:00+00:00
[2024-04-15T01:03:20.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 4.611 seconds
[2024-04-15T01:03:26.288+0000] {processor.py:161} INFO - Started process (PID=4172) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:26.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:03:26.290+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:26.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:28.353+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:28.520+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:28.518+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-13T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '20735987-b137-474f-9cc9-9a3b68de003c'}
[2024-04-15T01:03:28.578+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:28.578+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220313T000000, start_date=20240415T010250, end_date=20240415T010328
[2024-04-15T01:03:29.088+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-13T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:29.091+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.091+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-14T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '42dac104-9aff-4ddb-b307-fb694bbbbb1d'}
[2024-04-15T01:03:29.100+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.100+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220314T000000, start_date=20240415T010300, end_date=20240415T010329
[2024-04-15T01:03:29.104+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-14T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:29.107+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.107+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-12T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'eaa82fe9-f2b9-456f-a0b7-fe3a1a1e3a05'}
[2024-04-15T01:03:29.116+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.115+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220312T000000, start_date=20240415T010250, end_date=20240415T010329
[2024-04-15T01:03:29.118+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-12T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:29.121+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.120+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-15T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'bf0d2ed4-6f07-4826-a947-2bec9fd53d92'}
[2024-04-15T01:03:29.128+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.128+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220315T000000, start_date=20240415T010300, end_date=20240415T010329
[2024-04-15T01:03:29.132+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-15T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:29.134+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.134+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-14T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '42dac104-9aff-4ddb-b307-fb694bbbbb1d'}
[2024-04-15T01:03:29.142+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.142+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220314T000000, start_date=20240415T010300, end_date=20240415T010329
[2024-04-15T01:03:29.145+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-14T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:29.175+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.175+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:03:29.192+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:29.192+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-23 00:00:00+00:00, run_after=2022-03-24 00:00:00+00:00
[2024-04-15T01:03:29.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 2.938 seconds
[2024-04-15T01:03:36.925+0000] {processor.py:161} INFO - Started process (PID=4176) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:36.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:03:36.928+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:36.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:37.907+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:03:37.934+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:37.933+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-16T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd5577f19-694b-4db1-a27f-231512e13289'}
[2024-04-15T01:03:38.242+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.242+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220316T000000, start_date=20240415T010300, end_date=20240415T010337
[2024-04-15T01:03:38.252+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-16T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:38.255+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.255+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-15T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'bf0d2ed4-6f07-4826-a947-2bec9fd53d92'}
[2024-04-15T01:03:38.264+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.264+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220315T000000, start_date=20240415T010300, end_date=20240415T010338
[2024-04-15T01:03:38.269+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-15T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:38.272+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.271+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-17T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2ea383f4-a5fd-44fb-8dc0-2553eac6a2a6'}
[2024-04-15T01:03:38.282+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.281+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220317T000000, start_date=20240415T010311, end_date=20240415T010338
[2024-04-15T01:03:38.287+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-17T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:38.291+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.290+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-18T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '1d522fde-0f27-4a24-8d38-ca60da70b305'}
[2024-04-15T01:03:38.301+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.300+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220318T000000, start_date=20240415T010311, end_date=20240415T010338
[2024-04-15T01:03:38.304+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-18T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:38.307+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.307+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-16T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'd5577f19-694b-4db1-a27f-231512e13289'}
[2024-04-15T01:03:38.318+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.317+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220316T000000, start_date=20240415T010300, end_date=20240415T010338
[2024-04-15T01:03:38.321+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-16T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:03:38.335+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.335+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:03:38.354+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:03:38.354+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-26 00:00:00+00:00, run_after=2022-03-27 00:00:00+00:00
[2024-04-15T01:03:38.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.464 seconds
[2024-04-15T01:04:07.140+0000] {processor.py:161} INFO - Started process (PID=4221) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:04:07.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:04:07.148+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:07.147+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:04:08.448+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:04:08.480+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.479+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-19T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'dc42e25a-1bc0-4861-a578-d57dca0fb156'}
[2024-04-15T01:04:08.504+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.504+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220319T000000, start_date=20240415T010311, end_date=20240415T010408
[2024-04-15T01:04:08.517+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-19T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.522+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.521+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-17T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '2ea383f4-a5fd-44fb-8dc0-2553eac6a2a6'}
[2024-04-15T01:04:08.534+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.534+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220317T000000, start_date=20240415T010311, end_date=20240415T010408
[2024-04-15T01:04:08.539+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-17T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.542+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.542+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-18T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '1d522fde-0f27-4a24-8d38-ca60da70b305'}
[2024-04-15T01:04:08.554+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.554+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220318T000000, start_date=20240415T010311, end_date=20240415T010408
[2024-04-15T01:04:08.558+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-18T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.561+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.561+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-20T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0b8eaf41-a6be-40ec-90d1-f93921693193'}
[2024-04-15T01:04:08.573+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.573+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220320T000000, start_date=20240415T010323, end_date=20240415T010408
[2024-04-15T01:04:08.577+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-20T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.580+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.580+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-19T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'dc42e25a-1bc0-4861-a578-d57dca0fb156'}
[2024-04-15T01:04:08.589+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.588+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220319T000000, start_date=20240415T010311, end_date=20240415T010408
[2024-04-15T01:04:08.592+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-19T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.596+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.595+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-20T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '0b8eaf41-a6be-40ec-90d1-f93921693193'}
[2024-04-15T01:04:08.605+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.604+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220320T000000, start_date=20240415T010323, end_date=20240415T010408
[2024-04-15T01:04:08.609+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-20T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.613+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.613+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-21T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '1b57d6bb-9a25-46ac-bd4e-e539e20c7ca0'}
[2024-04-15T01:04:08.624+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.623+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220321T000000, start_date=20240415T010323, end_date=20240415T010408
[2024-04-15T01:04:08.627+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-21T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:08.643+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.642+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:04:08.664+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:08.663+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-03-29 00:00:00+00:00, run_after=2022-03-30 00:00:00+00:00
[2024-04-15T01:04:08.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 1.823 seconds
[2024-04-15T01:04:22.916+0000] {processor.py:161} INFO - Started process (PID=4254) to work on /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:04:22.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_equipment_failure_sensors.py for tasks to queue
[2024-04-15T01:04:22.920+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:22.919+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:04:38.384+0000] {processor.py:840} INFO - DAG(s) 'extract_and_load_equipment_failure_sensors' retrieved from /opt/airflow/dags/dag_equipment_failure_sensors.py
[2024-04-15T01:04:38.416+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.415+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-22T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f93c7ab7-8c96-4116-95e8-443b8eda1ef2'}
[2024-04-15T01:04:38.443+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.442+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220322T000000, start_date=20240415T010323, end_date=20240415T010438
[2024-04-15T01:04:38.457+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-22T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:38.462+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.461+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '79ac9589-d425-4bef-9231-c633f4a9e620'}
[2024-04-15T01:04:38.474+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.473+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220323T000000, start_date=20240415T010335, end_date=20240415T010438
[2024-04-15T01:04:38.478+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:38.483+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.482+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-22T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': 'f93c7ab7-8c96-4116-95e8-443b8eda1ef2'}
[2024-04-15T01:04:38.495+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.495+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220322T000000, start_date=20240415T010323, end_date=20240415T010438
[2024-04-15T01:04:38.503+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-22T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:38.507+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.507+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'extract_and_load_equipment_failure_sensors', 'Task Id': 'extract_data', 'Run Id': 'scheduled__2022-03-23T00:00:00+00:00', 'Hostname': '5844c8608a80', 'External Executor Id': '79ac9589-d425-4bef-9231-c633f4a9e620'}
[2024-04-15T01:04:38.522+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.521+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_failure_sensors, task_id=extract_data, execution_date=20220323T000000, start_date=20240415T010335, end_date=20240415T010438
[2024-04-15T01:04:38.526+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: extract_and_load_equipment_failure_sensors.extract_data scheduled__2022-03-23T00:00:00+00:00 [failed]> in state failed
[2024-04-15T01:04:38.548+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.547+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T01:04:38.881+0000] {logging_mixin.py:188} INFO - [2024-04-15T01:04:38.881+0000] {dag.py:3954} INFO - Setting next_dagrun for extract_and_load_equipment_failure_sensors to 2022-04-01 00:00:00+00:00, run_after=2022-04-02 00:00:00+00:00
[2024-04-15T01:04:38.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_equipment_failure_sensors.py took 15.951 seconds
